[project]
name = "audiobook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "keyboard>=0.13.5",
    "pypdf2>=3.0.1",
    "pyttsx3>=2.99",
]
